### ISSUE TITLE
Issue with path to compass binary

### ISSUE THREAD

**Issue by szimek** [mbuchetics/heroku-buildpack-nodejs-grunt#14]
I'm using [heroku-buildpack-multi](https://github.com/ddollar/heroku-buildpack-multi) to install `compass` library (Ruby) for Node.js app. I've been using Heroku Ruby and Node.js buildpacks and it worked fine. I switched to this one and suddenly Grunt task complains that it can't find compass binary:

```
Warning: Running "compass:dist" (compass) task
Warning: You need to have Ruby and Compass installed and in your system PATH for this task to work. More info: https://github.com/gruntjs/grunt-contrib-compass Use --force to continue.
```

It looks like `compass` is correctly installed to `/app/vendor/bundle/bin/compass` and `/app/vendor/bundle/bin` is in `PATH`.

Any idea what might be the problem?

**Comment by mbuchetics** [comment]
This buildpack is no longer maintained, please follow the official guidelines at https://devcenter.heroku.com/articles/node-with-grunt
