### ISSUE TITLE
Adding bower support

### ISSUE THREAD

**Issue by ezraroi** [mbuchetics/heroku-buildpack-nodejs-grunt#26]
My NodeJS app includes the server and client code, is it possible to add bower install phase before running the grunt task?

**Comment by mgiraldo** [comment]
did you ever manage to get it running? i also have a grunt/bower/node app and i can push to heroku just fine but my app doesnt run

**Comment by ezraroi** [comment]
Yes, I have forked the original heroku project and It is working for my project.
https://github.com/ezraroi/heroku-buildpack-nodejs

**Comment by mgiraldo** [comment]
what do you have in your `Procfile`?

**Comment by ezraroi** [comment]
I don't have Profile.
In my package.json I have:
"scripts": {
    "start": "node app.js"
  }

**Comment by mbuchetics** [comment]
This buildpack is no longer maintained, please follow the official guidelines at https://devcenter.heroku.com/articles/node-with-grunt
