### ISSUE TITLE
Procfile for Grunt/Bower/Node app?

### ISSUE THREAD

**Issue by mgiraldo** [mbuchetics/heroku-buildpack-nodejs-grunt#28]
what should the `Procfile` for a Grunt+Bower+Node app look like? I run the app locally using `grunt serve` but adding that command in the `Procfile` produces `grunt: command not found`. [this is my code](https://github.com/mgiraldo/inspectorviz)

**Comment by mbuchetics** [comment]
This buildpack is no longer maintained, please follow the official guidelines at https://devcenter.heroku.com/articles/node-with-grunt
