### ISSUE TITLE
Redirect to Dev Center article on node + grunt?

### ISSUE THREAD

**Issue by hunterloftis** [mbuchetics/heroku-buildpack-nodejs-grunt#29]
Heya, I maintain the node buildpack over at Heroku. With `grunt` + `grunt-cli` in dependencies, you can run grunt tasks on `postinstall` by default:

- https://devcenter.heroku.com/articles/node-with-grunt

What do you think of sending folks that way so they can keep up with regular buildpack updates while they use grunt?

**Comment by mbuchetics** [comment]
Thank you, I finally got around doing that. 
This buildback will no longer be maintained.
