### ISSUE TITLE
Allow setting NPM version in engines 

### ISSUE THREAD

**Issue by fabdrol** [mbuchetics/heroku-buildpack-nodejs-grunt#30]
Thuis buildpack ignores the `npm` setting in `engine` in `package.json`, causing issues for builds that break on `peerDependencies` (npm 3+ just generates a warning, instead of an error)

**Comment by mbuchetics** [comment]
This buildpack is no longer maintained, please follow the official guidelines at https://devcenter.heroku.com/articles/node-with-grunt
