### ISSUE TITLE
Typically, people use devDependencies for grunt components

### ISSUE THREAD

**Issue by caitp** [mbuchetics/heroku-buildpack-nodejs-grunt#5]
And it's kind of a hassle to add these dependencies to production as well -- so I'm thinking it might be a good idea to ensure that the devDependencies are installed, but the correct heroku:<NODE_ENV> task is still used?

I'm not totally sure in my head how this would work, since we can't tell heroku to change the value of NODE_ENV during compilation and deployment, as far as I can tell

**Comment by Edo78** [comment]
setting the npm production variable to false with

`heroku config:set NPM_CONFIG_PRODUCTION=false` 

would make heroku install everything under devDependencies https://devcenter.heroku.com/articles/nodejs-support

**Comment by renexdev** [comment]
Works for me Edo78. THks
